import type { Metadata } from 'next'
import { Libre_Franklin } from 'next/font/google'
import './globals.css'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const libre = Libre_Franklin({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ping-coming-soon-page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={libre.className}>{children}</body>
    </html>
  )
}
